// Starter MCP server map generated by NexusBrowser.
// Wire this into @modelcontextprotocol/sdk and put credentials in environment variables.

export const discoveredTools = {
  "get_daytonabeach_gov_antiforgery": {
    endpoint: "https://daytonabeach.gov/antiforgery",
    method: "GET",
    requiresAuth: false,
  },
  "get_daytonabeach_gov_Toggle": {
    endpoint: "https://daytonabeach.gov/Toggle",
    method: "GET",
    requiresAuth: false,
  },
  "get_residentagent_api_production_azurewebsites_net_api_v1_public_agents_3e4af47e": {
    endpoint: "https://residentagent-api-production.azurewebsites.net/api/v1/public/agents/3e4af47e-b3e9-4b83-8bc1-ab65735efc32/configuration",
    method: "GET",
    requiresAuth: false,
  },
  "get_daytonabeach_gov_Pages_MenuMain_HiddenMainSubMenus": {
    endpoint: "https://daytonabeach.gov/Pages/MenuMain/HiddenMainSubMenus?pageID=%7BpageID%7D&moduleID=%7BmoduleID%7D&themeID=%7BthemeID%7D&menuContainerID=%7BmenuContainerID%7D&_=%7B_%7D",
    method: "GET",
    requiresAuth: false,
  },
  "get_daytonabeach_gov_api_v1_SplashModal_Get": {
    endpoint: "https://daytonabeach.gov/api/v1/SplashModal/Get?targetId=%7BtargetId%7D&targetType=%7BtargetType%7D&requestMode=%7BrequestMode%7D&_=%7B_%7D",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_muli_v34_7Auwp_0qiz_afTLGLQ_woff2": {
    endpoint: "https://fonts.gstatic.com/s/muli/v34/7Auwp_0qiz-afTLGLQ.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_muli_v34_7Aujp_0qiz_afTfcIyoiGtm2P0wG05Fz4eqVww_woff2": {
    endpoint: "https://fonts.gstatic.com/s/muli/v34/7Aujp_0qiz-afTfcIyoiGtm2P0wG05Fz4eqVww.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_poppins_v24_pxiByp8kv8JHgFVrLCz7Z1xlFQ_woff2": {
    endpoint: "https://fonts.gstatic.com/s/poppins/v24/pxiByp8kv8JHgFVrLCz7Z1xlFQ.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_poppins_v24_pxiEyp8kv8JHgFVrJJfecg_woff2": {
    endpoint: "https://fonts.gstatic.com/s/poppins/v24/pxiEyp8kv8JHgFVrJJfecg.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_poppins_v24_pxiByp8kv8JHgFVrLEj6Z1xlFQ_woff2": {
    endpoint: "https://fonts.gstatic.com/s/poppins/v24/pxiByp8kv8JHgFVrLEj6Z1xlFQ.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_yellowtail_v25_OZpGg_pnoDtINPfRIlLohlvHwQ_woff2": {
    endpoint: "https://fonts.gstatic.com/s/yellowtail/v25/OZpGg_pnoDtINPfRIlLohlvHwQ.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_opensans_v44_memvYaGs126MiZpBA_UvWbX2vVnXBbObj2OVTS_muw_": {
    endpoint: "https://fonts.gstatic.com/s/opensans/v44/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_fonts_gstatic_com_s_poppins_v24_pxiByp8kv8JHgFVrLGT9Z1xlFQ_woff2": {
    endpoint: "https://fonts.gstatic.com/s/poppins/v24/pxiByp8kv8JHgFVrLGT9Z1xlFQ.woff2",
    method: "GET",
    requiresAuth: false,
  },
  "get_docaccess_com_domains_daytonabeach_gov_domain_json": {
    endpoint: "https://docaccess.com/domains/daytonabeach.gov/domain.json",
    method: "GET",
    requiresAuth: false,
  },
  "post_www_google_analytics_com_g_collect": {
    endpoint: "https://www.google-analytics.com/g/collect?v=%7Bv%7D&tid=%7Btid%7D&gtm=%7Bgtm%7D&_p=%7B_p%7D&gcd=%7Bgcd%7D&npa=%7Bnpa%7D&dma=%7Bdma%7D&cid=%7Bcid%7D&frm=%7Bfrm%7D&ngs=%7Bngs%7D&pscdl=%7Bpscdl%7D&rcb=%7Brcb%7D&sr=%7Bsr%7D&uaa=%7Buaa%7D&uab=%7Buab%7D&uafvl=%7Buafvl%7D&uam=%7Buam%7D&uamb=%7Buamb%7D&uap=%7Buap%7D&uapv=%7Buapv%7D&uaw=%7Buaw%7D&ul=%7Bul%7D&_s=%7B_s%7D&tag_exp=%7Btag_exp%7D&sid=%7Bsid%7D&sct=%7Bsct%7D&seg=%7Bseg%7D&dl=%7Bdl%7D&dt=%7Bdt%7D&en=%7Ben%7D&_fv=%7B_fv%7D&_nsi=%7B_nsi%7D&_ss=%7B_ss%7D&_ee=%7B_ee%7D&tfd=%7Btfd%7D",
    method: "POST",
    requiresAuth: false,
  },
  "post_www_google_analytics_com_g_collect": {
    endpoint: "https://www.google-analytics.com/g/collect?v=%7Bv%7D&tid=%7Btid%7D&gtm=%7Bgtm%7D&_p=%7B_p%7D&gcd=%7Bgcd%7D&npa=%7Bnpa%7D&dma=%7Bdma%7D&cid=%7Bcid%7D&frm=%7Bfrm%7D&ngs=%7Bngs%7D&pscdl=%7Bpscdl%7D&rcb=%7Brcb%7D&sr=%7Bsr%7D&uaa=%7Buaa%7D&uab=%7Buab%7D&uafvl=%7Buafvl%7D&uam=%7Buam%7D&uamb=%7Buamb%7D&uap=%7Buap%7D&uapv=%7Buapv%7D&uaw=%7Buaw%7D&ul=%7Bul%7D&_s=%7B_s%7D&tag_exp=%7Btag_exp%7D&sid=%7Bsid%7D&sct=%7Bsct%7D&seg=%7Bseg%7D&dl=%7Bdl%7D&dt=%7Bdt%7D&en=%7Ben%7D&_fv=%7B_fv%7D&_ss=%7B_ss%7D&tfd=%7Btfd%7D",
    method: "POST",
    requiresAuth: false,
  }
};

export async function callDiscoveredTool(name: keyof typeof discoveredTools, input: Record<string, unknown>) {
  const tool = discoveredTools[name];
  const url = new URL(tool.endpoint);

  for (const [key, value] of Object.entries(input)) {
    if (key !== 'body' && value !== undefined) url.searchParams.set(key, String(value));
  }

  const headers: Record<string, string> = { accept: 'application/json' };
  if (tool.requiresAuth && process.env.API_AUTH_TOKEN) headers.authorization = `Bearer ${process.env.API_AUTH_TOKEN}`;

  const response = await fetch(url, {
    method: tool.method,
    headers,
    body: tool.method === 'GET' ? undefined : JSON.stringify(input.body || {}),
  });

  return {
    status: response.status,
    contentType: response.headers.get('content-type'),
    body: await response.text(),
  };
}
