export interface LanguageExpertProfile {
  id: string;
  name: string;
  category: 'language' | 'runtime' | 'frontend' | 'backend' | 'database' | 'database-service' | 'orm' | 'package-manager' | 'package-registry' | 'build-tool' | 'test-tool' | 'devops' | 'cloud' | 'api' | 'protocol' | 'security' | 'auth' | 'payments' | 'mobile' | 'ai' | 'observability' | 'search' | 'message-queue' | 'storage' | 'cms' | 'monorepo' | 'compliance' | 'boilerplate' | 'design-system' | 'ux' | 'animation' | 'graphics' | 'document' | 'serverless' | 'library';
  role: string;
  officialGithub: string;
  docs: string[];
  filePatterns: string[];
  packageSignals: string[];
  checks: string[];
  repairSkills: string[];
}

export interface LanguageUpdateReport {
  id: string;
  name: string;
  officialGithub: string;
  fetchedAt: string;
  latestRelease?: { tag: string; name: string; publishedAt?: string; url?: string; notes?: string };
  repo?: { stars?: number; openIssues?: number; defaultBranch?: string; pushedAt?: string };
  prompt: string;
}

const languageExperts: LanguageExpertProfile[] = [
  expert('typescript', 'TypeScript Expert Agent', 'language', 'microsoft/TypeScript', ['https://www.typescriptlang.org/docs/', 'https://github.com/microsoft/TypeScript/releases'], ['tsconfig.json', 'src/**/*.ts', 'src/**/*.tsx'], ['typescript', '@types/node', '@types/react'], ['tsconfig validity', 'strict-mode errors', 'module resolution', 'JSX config', 'missing @types packages'], ['fix compiler options', 'add missing types', 'repair imports/exports', 'align framework type settings']),
  expert('javascript', 'JavaScript Expert Agent', 'language', 'tc39/ecma262', ['https://tc39.es/ecma262/', 'https://github.com/tc39/proposals'], ['src/**/*.js', 'src/**/*.mjs', 'package.json'], ['eslint', 'prettier'], ['ESM/CJS usage', 'modern syntax support', 'runtime compatibility'], ['repair syntax/runtime mismatches', 'fix module boundaries', 'modernize safely']),
  expert('python', 'Python Expert Agent', 'language', 'python/cpython', ['https://docs.python.org/3/', 'https://github.com/python/cpython/releases'], ['**/*.py', 'pyproject.toml', 'requirements.txt'], ['python', 'pytest', 'ruff', 'fastapi', 'django'], ['Python version', 'dependency spec', 'import paths', 'venv assumptions'], ['fix packaging', 'repair imports', 'add pyproject config', 'stabilize tests']),
  expert('go', 'Go Expert Agent', 'language', 'golang/go', ['https://go.dev/doc/', 'https://github.com/golang/go/releases'], ['go.mod', '**/*.go'], ['go'], ['module path', 'go version', 'formatting', 'race/test failures'], ['fix go.mod', 'repair imports', 'run gofmt', 'stabilize tests']),
  expert('rust', 'Rust Expert Agent', 'language', 'rust-lang/rust', ['https://doc.rust-lang.org/book/', 'https://github.com/rust-lang/rust/releases'], ['Cargo.toml', '**/*.rs'], ['cargo', 'rustc'], ['borrow/type errors', 'crate features', 'edition compatibility'], ['fix Cargo features', 'repair ownership issues', 'stabilize clippy/test failures']),
  expert('php', 'PHP Expert Agent', 'language', 'php/php-src', ['https://www.php.net/docs.php', 'https://github.com/php/php-src/releases'], ['composer.json', '**/*.php'], ['composer', 'phpunit', 'laravel/framework'], ['PHP version', 'composer autoload', 'namespace errors'], ['fix composer config', 'repair namespaces', 'add env/config guidance']),
  expert('java', 'Java Expert Agent', 'language', 'openjdk/jdk', ['https://docs.oracle.com/en/java/', 'https://github.com/openjdk/jdk'], ['pom.xml', 'build.gradle', '**/*.java'], ['maven', 'gradle', 'spring-boot'], ['JDK version', 'Maven/Gradle config', 'package/classpath errors'], ['fix build config', 'repair imports', 'align JDK target']),
  expert('csharp-dotnet', '.NET/C# Expert Agent', 'language', 'dotnet/runtime', ['https://learn.microsoft.com/dotnet/', 'https://github.com/dotnet/runtime/releases'], ['*.csproj', '*.sln', '**/*.cs'], ['dotnet', 'aspnetcore'], ['target framework', 'NuGet restore', 'nullable errors'], ['fix csproj', 'repair package refs', 'stabilize dotnet build/test']),
  expert('swift', 'Swift Expert Agent', 'language', 'swiftlang/swift', ['https://www.swift.org/documentation/', 'https://github.com/swiftlang/swift/releases'], ['Package.swift', '**/*.swift'], ['swift'], ['Swift version', 'package resolution', 'platform target'], ['fix Package.swift', 'repair imports', 'align platform targets']),
  expert('kotlin', 'Kotlin Expert Agent', 'language', 'JetBrains/kotlin', ['https://kotlinlang.org/docs/home.html', 'https://github.com/JetBrains/kotlin/releases'], ['build.gradle.kts', '**/*.kt'], ['kotlin', 'gradle'], ['Kotlin version', 'Gradle plugin config', 'JVM target'], ['fix Gradle Kotlin config', 'repair source sets', 'align JVM target']),
  expert('ruby', 'Ruby Expert Agent', 'language', 'ruby/ruby', ['https://www.ruby-lang.org/en/documentation/', 'https://github.com/ruby/ruby/releases'], ['Gemfile', '**/*.rb'], ['bundler', 'rails'], ['Ruby version', 'bundle install', 'autoload/constants'], ['fix Gemfile', 'repair Rails config', 'stabilize tests']),
  expert('node', 'Node.js Runtime Expert Agent', 'runtime', 'nodejs/node', ['https://nodejs.org/en/docs', 'https://github.com/nodejs/node/releases'], ['package.json', 'src/**/*.ts', 'src/**/*.js'], ['node', 'tsx', 'ts-node'], ['engine mismatch', 'ESM/CJS mismatch', 'script failures', 'env handling'], ['fix scripts', 'align module type', 'repair server startup', 'add env validation']),
  expert('bun', 'Bun Expert Agent', 'runtime', 'oven-sh/bun', ['https://bun.sh/docs', 'https://github.com/oven-sh/bun/releases'], ['bun.lockb', 'package.json'], ['bun'], ['Bun runtime compatibility', 'lockfile use', 'script behavior'], ['fix Bun scripts', 'repair package manager assumptions', 'align runtime APIs']),
  expert('deno', 'Deno Expert Agent', 'runtime', 'denoland/deno', ['https://docs.deno.com/', 'https://github.com/denoland/deno/releases'], ['deno.json', '**/*.ts'], ['deno'], ['permissions', 'imports', 'tasks', 'Node compatibility'], ['fix deno.json', 'repair imports', 'add permissions safely']),
  expert('react', 'React Expert Agent', 'frontend', 'facebook/react', ['https://react.dev/', 'https://github.com/facebook/react/releases'], ['src/**/*.jsx', 'src/**/*.tsx'], ['react', 'react-dom'], ['invalid hooks', 'root render', 'hydration risks', 'accessibility'], ['fix render errors', 'repair component boundaries', 'wire loading/error states']),
  expert('nextjs', 'Next.js Expert Agent', 'frontend', 'vercel/next.js', ['https://nextjs.org/docs', 'https://github.com/vercel/next.js/releases'], ['next.config.*', 'app/**', 'pages/**'], ['next'], ['app router', 'server/client boundary', 'route handlers', 'env usage'], ['fix Next config', 'repair client/server components', 'stabilize build']),
  expert('vue', 'Vue Expert Agent', 'frontend', 'vuejs/core', ['https://vuejs.org/guide/introduction.html', 'https://github.com/vuejs/core/releases'], ['src/**/*.vue', 'vite.config.*'], ['vue', '@vitejs/plugin-vue'], ['SFC compile', 'reactivity usage', 'plugin config'], ['fix SFCs', 'repair Vite plugin', 'stabilize build']),
  expert('svelte', 'Svelte Expert Agent', 'frontend', 'sveltejs/svelte', ['https://svelte.dev/docs', 'https://github.com/sveltejs/svelte/releases'], ['src/**/*.svelte', 'svelte.config.*'], ['svelte', '@sveltejs/kit'], ['component compile', 'Kit config', 'routing'], ['fix components', 'repair Kit config', 'stabilize build']),
  expert('angular', 'Angular Expert Agent', 'frontend', 'angular/angular', ['https://angular.dev/', 'https://github.com/angular/angular/releases'], ['angular.json', 'src/**/*.ts', 'src/**/*.html'], ['@angular/core', '@angular/cli'], ['Angular version', 'module/standalone setup', 'template errors'], ['fix Angular config', 'repair templates', 'align dependencies']),
  expert('tailwind', 'Tailwind CSS Expert Agent', 'frontend', 'tailwindlabs/tailwindcss', ['https://tailwindcss.com/docs', 'https://github.com/tailwindlabs/tailwindcss/releases'], ['tailwind.config.*', 'src/**/*.{ts,tsx,js,jsx,css}'], ['tailwindcss', '@tailwindcss/vite'], ['content paths', 'theme tokens', 'class generation', 'PostCSS/Vite plugin'], ['fix Tailwind config', 'repair theme tokens', 'stabilize styling pipeline']),
  expert('express', 'Express Expert Agent', 'backend', 'expressjs/express', ['https://expressjs.com/', 'https://github.com/expressjs/express/releases'], ['server.*', 'src/**/*.{ts,js}'], ['express'], ['middleware order', 'routing', 'error handling', 'CORS/security'], ['fix routes', 'repair middleware', 'add safe error handling']),
  expert('fastapi', 'FastAPI Expert Agent', 'backend', 'fastapi/fastapi', ['https://fastapi.tiangolo.com/', 'https://github.com/fastapi/fastapi/releases'], ['**/*.py', 'pyproject.toml'], ['fastapi', 'uvicorn', 'pydantic'], ['ASGI startup', 'Pydantic models', 'routing', 'OpenAPI'], ['fix app startup', 'repair models', 'stabilize API tests']),
  expert('django', 'Django Expert Agent', 'backend', 'django/django', ['https://docs.djangoproject.com/', 'https://github.com/django/django/releases'], ['manage.py', '**/*.py'], ['django'], ['settings', 'migrations', 'URLs', 'templates'], ['fix settings', 'repair migrations', 'stabilize server/tests']),
  expert('laravel', 'Laravel Expert Agent', 'backend', 'laravel/framework', ['https://laravel.com/docs', 'https://github.com/laravel/framework/releases'], ['artisan', 'composer.json', '**/*.php'], ['laravel/framework'], ['env config', 'routes', 'migrations', 'composer scripts'], ['fix Laravel config', 'repair routes', 'stabilize migrations']),
  expert('postgres', 'PostgreSQL Expert Agent', 'database', 'postgres/postgres', ['https://www.postgresql.org/docs/', 'https://github.com/postgres/postgres'], ['**/*.sql', 'schema.prisma', 'drizzle.config.*'], ['pg', 'postgres', '@prisma/client'], ['schema types', 'indexes', 'migrations', 'connection env'], ['repair schema', 'add indexes', 'fix migrations', 'document DATABASE_URL']),
  expert('mysql', 'MySQL Expert Agent', 'database', 'mysql/mysql-server', ['https://dev.mysql.com/doc/', 'https://github.com/mysql/mysql-server'], ['**/*.sql', 'prisma/schema.prisma'], ['mysql2', 'mysql'], ['SQL dialect', 'migrations', 'connection env'], ['repair MySQL schema', 'fix queries', 'document env vars']),
  expert('sqlite', 'SQLite Expert Agent', 'database', 'sqlite/sqlite', ['https://www.sqlite.org/docs.html', 'https://github.com/sqlite/sqlite'], ['*.sqlite', '**/*.sql', 'prisma/schema.prisma'], ['sqlite3', 'better-sqlite3', '@libsql/client'], ['local schema', 'foreign keys', 'migration safety'], ['repair local schema', 'add seed data', 'fix SQLite dialect']),
  expert('mongodb', 'MongoDB Expert Agent', 'database', 'mongodb/mongo', ['https://www.mongodb.com/docs/', 'https://github.com/mongodb/mongo'], ['**/*.schema.*', 'src/**/*.{ts,js}'], ['mongodb', 'mongoose'], ['connection string', 'schema models', 'indexes'], ['fix connection config', 'repair models', 'add index guidance']),
  expert('redis', 'Redis Expert Agent', 'database', 'redis/redis', ['https://redis.io/docs/latest/', 'https://github.com/redis/redis/releases'], ['src/**/*.{ts,js,py}', 'docker-compose.yml'], ['redis', 'ioredis'], ['cache keys', 'connection env', 'TTL policy'], ['fix Redis client config', 'add cache fallbacks', 'document env vars']),
  expert('prisma', 'Prisma Expert Agent', 'orm', 'prisma/prisma', ['https://www.prisma.io/docs', 'https://github.com/prisma/prisma/releases'], ['prisma/schema.prisma', 'package.json'], ['prisma', '@prisma/client'], ['schema validity', 'generate/migrate scripts', 'DATABASE_URL'], ['fix Prisma schema', 'repair migrations', 'add generate scripts']),
  expert('drizzle', 'Drizzle ORM Expert Agent', 'orm', 'drizzle-team/drizzle-orm', ['https://orm.drizzle.team/docs/overview', 'https://github.com/drizzle-team/drizzle-orm/releases'], ['drizzle.config.*', 'src/**/schema.*'], ['drizzle-orm', 'drizzle-kit'], ['schema exports', 'migration config', 'driver mismatch'], ['fix Drizzle config', 'repair schema', 'stabilize migrations']),
  expert('npm', 'npm Expert Agent', 'package-manager', 'npm/cli', ['https://docs.npmjs.com/', 'https://github.com/npm/cli/releases'], ['package.json', 'package-lock.json'], ['npm'], ['lockfile state', 'scripts', 'dependency ranges', 'install failures'], ['fix package scripts', 'repair lock/deps', 'stabilize npm install']),
  expert('pnpm', 'pnpm Expert Agent', 'package-manager', 'pnpm/pnpm', ['https://pnpm.io/motivation', 'https://github.com/pnpm/pnpm/releases'], ['pnpm-lock.yaml', 'package.json', 'pnpm-workspace.yaml'], ['pnpm'], ['workspace config', 'strict node_modules', 'lockfile'], ['fix workspace config', 'repair dependency resolution', 'stabilize install']),
  expert('yarn', 'Yarn Expert Agent', 'package-manager', 'yarnpkg/berry', ['https://yarnpkg.com/', 'https://github.com/yarnpkg/berry/releases'], ['yarn.lock', '.yarnrc.yml', 'package.json'], ['yarn'], ['PnP/node_modules mode', 'workspace config', 'lockfile'], ['fix Yarn config', 'repair workspace deps', 'stabilize install']),
  expert('vite', 'Vite Expert Agent', 'build-tool', 'vitejs/vite', ['https://vite.dev/guide/', 'https://github.com/vitejs/vite/releases'], ['vite.config.ts', 'vite.config.js', 'index.html'], ['vite', '@vitejs/plugin-react'], ['dev script', 'build script', 'entry module', 'plugin config', 'env naming'], ['fix Vite config', 'repair index.html entry', 'resolve transform errors']),
  expert('webpack', 'Webpack Expert Agent', 'build-tool', 'webpack/webpack', ['https://webpack.js.org/concepts/', 'https://github.com/webpack/webpack/releases'], ['webpack.config.*'], ['webpack', 'webpack-cli'], ['loader config', 'entry/output', 'module resolution'], ['fix loaders', 'repair config', 'stabilize build']),
  expert('esbuild', 'esbuild Expert Agent', 'build-tool', 'evanw/esbuild', ['https://esbuild.github.io/', 'https://github.com/evanw/esbuild/releases'], ['package.json', 'build.*'], ['esbuild'], ['target/platform config', 'loader errors', 'bundle output'], ['fix esbuild config', 'repair loaders', 'align target/platform']),
  expert('eslint', 'ESLint Expert Agent', 'test-tool', 'eslint/eslint', ['https://eslint.org/docs/latest/', 'https://github.com/eslint/eslint/releases'], ['eslint.config.*', '.eslintrc.*'], ['eslint', 'typescript-eslint'], ['flat config', 'parser plugins', 'lint failures'], ['fix ESLint config', 'repair parser setup', 'reduce false positives']),
  expert('prettier', 'Prettier Expert Agent', 'test-tool', 'prettier/prettier', ['https://prettier.io/docs/en/', 'https://github.com/prettier/prettier/releases'], ['.prettierrc*', 'package.json'], ['prettier'], ['format scripts', 'parser support', 'ignore config'], ['fix formatting config', 'repair scripts', 'add ignore rules']),
  expert('jest', 'Jest Expert Agent', 'test-tool', 'jestjs/jest', ['https://jestjs.io/docs/getting-started', 'https://github.com/jestjs/jest/releases'], ['jest.config.*', '**/*.test.*'], ['jest', 'ts-jest'], ['transform config', 'test env', 'module aliases'], ['fix Jest config', 'repair transforms', 'stabilize tests']),
  expert('vitest', 'Vitest Expert Agent', 'test-tool', 'vitest-dev/vitest', ['https://vitest.dev/guide/', 'https://github.com/vitest-dev/vitest/releases'], ['vitest.config.*', 'vite.config.*'], ['vitest'], ['test env', 'Vite config reuse', 'coverage'], ['fix Vitest config', 'repair jsdom setup', 'stabilize tests']),
  expert('playwright', 'Playwright Expert Agent', 'test-tool', 'microsoft/playwright', ['https://playwright.dev/docs/intro', 'https://github.com/microsoft/playwright/releases'], ['playwright.config.*', 'tests/**/*.spec.*'], ['playwright', '@playwright/test'], ['browser install', 'selectors', 'timeouts', 'visual tests'], ['fix Playwright config', 'repair tests', 'add stable locators']),
  expert('docker', 'Docker Expert Agent', 'devops', 'moby/moby', ['https://docs.docker.com/', 'https://github.com/moby/moby/releases'], ['Dockerfile', 'docker-compose.yml'], ['docker'], ['image build', 'ports', 'env vars', 'multi-stage builds'], ['fix Dockerfile', 'repair compose', 'document runtime env']),
  expert('kubernetes', 'Kubernetes Expert Agent', 'devops', 'kubernetes/kubernetes', ['https://kubernetes.io/docs/home/', 'https://github.com/kubernetes/kubernetes/releases'], ['k8s/**/*.yaml', 'helm/**'], ['kubectl', 'helm'], ['manifests', 'services', 'ingress', 'secrets'], ['fix manifests', 'repair service wiring', 'add secret guidance']),
  expert('terraform', 'Terraform Expert Agent', 'devops', 'hashicorp/terraform', ['https://developer.hashicorp.com/terraform/docs', 'https://github.com/hashicorp/terraform/releases'], ['**/*.tf'], ['terraform'], ['provider versions', 'state/backend config', 'variables'], ['fix Terraform config', 'repair variables', 'document plan/apply']),
  expert('github-actions', 'GitHub Actions Expert Agent', 'devops', 'actions/runner', ['https://docs.github.com/actions', 'https://github.com/actions/runner/releases'], ['.github/workflows/*.yml'], ['github-actions'], ['workflow syntax', 'secrets', 'caching', 'CI scripts'], ['fix workflows', 'repair caches', 'add safe deploy gates']),
  expert('vercel', 'Vercel Expert Agent', 'cloud', 'vercel/vercel', ['https://vercel.com/docs', 'https://github.com/vercel/vercel/releases'], ['vercel.json', 'next.config.*'], ['vercel'], ['framework detection', 'env vars', 'build command', 'output directory'], ['fix Vercel config', 'repair env docs', 'stabilize deploy']),
  expert('netlify', 'Netlify Expert Agent', 'cloud', 'netlify/cli', ['https://docs.netlify.com/', 'https://github.com/netlify/cli/releases'], ['netlify.toml'], ['netlify-cli'], ['build command', 'publish dir', 'functions', 'env vars'], ['fix Netlify config', 'repair redirects/functions', 'document deploy']),
  expert('cloudflare', 'Cloudflare Workers Expert Agent', 'cloud', 'cloudflare/workers-sdk', ['https://developers.cloudflare.com/workers/', 'https://github.com/cloudflare/workers-sdk/releases'], ['wrangler.toml', 'worker.*'], ['wrangler'], ['bindings', 'compatibility date', 'routes', 'env vars'], ['fix wrangler config', 'repair bindings', 'stabilize worker deploy']),
  expert('openapi', 'OpenAPI Expert Agent', 'api', 'OAI/OpenAPI-Specification', ['https://spec.openapis.org/oas/latest.html', 'https://github.com/OAI/OpenAPI-Specification'], ['openapi.json', 'openapi.yaml'], ['openapi-typescript', 'swagger-ui'], ['schema validity', 'paths/methods', 'auth schemes'], ['repair OpenAPI docs', 'generate SDK inputs', 'add auth schemas']),
  expert('graphql', 'GraphQL Expert Agent', 'api', 'graphql/graphql-js', ['https://graphql.org/learn/', 'https://github.com/graphql/graphql-js/releases'], ['schema.graphql', 'src/**/*.graphql'], ['graphql', '@apollo/client'], ['schema validity', 'queries/mutations', 'resolver/client types'], ['fix GraphQL schema', 'repair client queries', 'add typed codegen']),
  expert('authjs', 'Auth.js Expert Agent', 'auth', 'nextauthjs/next-auth', ['https://authjs.dev/', 'https://github.com/nextauthjs/next-auth/releases'], ['auth.*', 'middleware.*', '.env.example'], ['next-auth', '@auth/core'], ['providers', 'callbacks', 'session strategy', 'env secrets'], ['fix auth config', 'repair callbacks', 'document secrets']),
  expert('clerk', 'Clerk Expert Agent', 'auth', 'clerk/javascript', ['https://clerk.com/docs', 'https://github.com/clerk/javascript/releases'], ['middleware.*', 'src/**/*.{ts,tsx}'], ['@clerk/nextjs', '@clerk/clerk-react'], ['publishable/secret keys', 'middleware', 'protected routes'], ['fix Clerk config', 'repair route protection', 'document env vars']),
  expert('stripe', 'Stripe Expert Agent', 'payments', 'stripe/stripe-node', ['https://docs.stripe.com/', 'https://github.com/stripe/stripe-node/releases'], ['src/**/*.{ts,js}', '.env.example'], ['stripe'], ['checkout sessions', 'webhooks', 'price IDs', 'signature verification'], ['fix Stripe client/routes', 'repair webhook handling', 'document env vars']),
  expert('react-native', 'React Native Expert Agent', 'mobile', 'facebook/react-native', ['https://reactnative.dev/docs/getting-started', 'https://github.com/facebook/react-native/releases'], ['app.json', 'metro.config.*', 'src/**/*.{tsx,jsx}'], ['react-native', 'expo'], ['Metro config', 'native dependencies', 'platform files'], ['fix Metro config', 'repair dependencies', 'stabilize mobile build']),
  expert('expo', 'Expo Expert Agent', 'mobile', 'expo/expo', ['https://docs.expo.dev/', 'https://github.com/expo/expo/releases'], ['app.json', 'app.config.*'], ['expo'], ['SDK version', 'plugins', 'native config'], ['fix Expo config', 'repair plugins', 'document build profile']),
  expert('openai', 'OpenAI SDK Expert Agent', 'ai', 'openai/openai-node', ['https://platform.openai.com/docs', 'https://github.com/openai/openai-node/releases'], ['src/**/*.{ts,js}', '.env.example'], ['openai'], ['API key env', 'model usage', 'streaming/tools', 'error handling'], ['fix client setup', 'repair env handling', 'add safe fallbacks']),
  expert('anthropic', 'Anthropic SDK Expert Agent', 'ai', 'anthropics/anthropic-sdk-typescript', ['https://docs.anthropic.com/', 'https://github.com/anthropics/anthropic-sdk-typescript/releases'], ['src/**/*.{ts,js}', '.env.example'], ['@anthropic-ai/sdk'], ['API key env', 'messages API', 'tool use', 'streaming'], ['fix client setup', 'repair tool schemas', 'document env vars']),
  expert('sentry', 'Sentry Expert Agent', 'observability', 'getsentry/sentry-javascript', ['https://docs.sentry.io/platforms/javascript/', 'https://github.com/getsentry/sentry-javascript/releases'], ['sentry.*', 'src/**/*.{ts,tsx,js,jsx}'], ['@sentry/react', '@sentry/nextjs'], ['DSN env', 'source maps', 'error boundaries'], ['fix Sentry config', 'repair source maps', 'add error boundaries']),
  expert('c', 'C Expert Agent', 'language', 'gcc-mirror/gcc', ['https://gcc.gnu.org/onlinedocs/', 'https://github.com/gcc-mirror/gcc'], ['**/*.c', '**/*.h', 'Makefile', 'CMakeLists.txt'], ['gcc', 'clang', 'make', 'cmake'], ['compiler flags', 'header paths', 'linker errors', 'memory safety'], ['fix build flags', 'repair includes', 'stabilize linker setup']),
  expert('cpp', 'C++ Expert Agent', 'language', 'llvm/llvm-project', ['https://isocpp.org/', 'https://github.com/llvm/llvm-project/releases'], ['**/*.cpp', '**/*.hpp', 'CMakeLists.txt'], ['clang', 'gcc', 'cmake', 'conan', 'vcpkg'], ['standard version', 'template errors', 'ABI/linking', 'CMake config'], ['fix CMake targets', 'repair includes', 'align C++ standard']),
  expert('zig', 'Zig Expert Agent', 'language', 'ziglang/zig', ['https://ziglang.org/documentation/master/', 'https://github.com/ziglang/zig/releases'], ['build.zig', '**/*.zig'], ['zig'], ['Zig version', 'build.zig config', 'compile errors'], ['fix build.zig', 'repair imports', 'align target settings']),
  expert('elixir', 'Elixir Expert Agent', 'language', 'elixir-lang/elixir', ['https://elixir-lang.org/docs.html', 'https://github.com/elixir-lang/elixir/releases'], ['mix.exs', '**/*.ex', '**/*.exs'], ['mix', 'phoenix'], ['OTP version', 'Mix deps', 'supervision tree'], ['fix mix config', 'repair modules', 'stabilize tests']),
  expert('erlang', 'Erlang Expert Agent', 'language', 'erlang/otp', ['https://www.erlang.org/docs', 'https://github.com/erlang/otp/releases'], ['rebar.config', '**/*.erl', '**/*.hrl'], ['rebar3', 'erlang'], ['OTP compatibility', 'application config', 'release build'], ['fix rebar config', 'repair app files', 'stabilize release']),
  expert('scala', 'Scala Expert Agent', 'language', 'scala/scala3', ['https://docs.scala-lang.org/', 'https://github.com/scala/scala3/releases'], ['build.sbt', '**/*.scala'], ['sbt', 'scala'], ['Scala version', 'sbt plugins', 'type errors'], ['fix sbt config', 'repair imports', 'align JVM target']),
  expert('dart', 'Dart Expert Agent', 'language', 'dart-lang/sdk', ['https://dart.dev/guides', 'https://github.com/dart-lang/sdk/releases'], ['pubspec.yaml', '**/*.dart'], ['dart', 'flutter'], ['SDK constraints', 'pub deps', 'analysis errors'], ['fix pubspec', 'repair imports', 'stabilize analyzer/tests']),
  expert('flutter', 'Flutter Expert Agent', 'mobile', 'flutter/flutter', ['https://docs.flutter.dev/', 'https://github.com/flutter/flutter/releases'], ['pubspec.yaml', 'lib/**/*.dart'], ['flutter'], ['SDK channel', 'platform config', 'widget build errors'], ['fix pubspec', 'repair platform config', 'stabilize Flutter build']),
  expert('r', 'R Expert Agent', 'language', 'wch/r-source', ['https://cran.r-project.org/manuals.html', 'https://github.com/wch/r-source'], ['DESCRIPTION', '**/*.R', '**/*.Rmd'], ['r', 'renv', 'shiny'], ['package metadata', 'library paths', 'Shiny runtime'], ['fix DESCRIPTION', 'repair dependencies', 'stabilize scripts']),
  expert('julia', 'Julia Expert Agent', 'language', 'JuliaLang/julia', ['https://docs.julialang.org/', 'https://github.com/JuliaLang/julia/releases'], ['Project.toml', '**/*.jl'], ['julia'], ['Project/Manifest', 'package precompile', 'version bounds'], ['fix Project.toml', 'repair imports', 'stabilize tests']),
  expert('lua', 'Lua Expert Agent', 'language', 'lua/lua', ['https://www.lua.org/manual/', 'https://github.com/lua/lua'], ['**/*.lua', 'rockspec'], ['lua', 'luarocks'], ['Lua version', 'module paths', 'rockspec'], ['fix module paths', 'repair rockspec', 'stabilize runtime']),
  expert('haskell', 'Haskell Expert Agent', 'language', 'ghc/ghc', ['https://www.haskell.org/documentation/', 'https://github.com/ghc/ghc'], ['*.cabal', 'stack.yaml', '**/*.hs'], ['ghc', 'cabal', 'stack'], ['GHC version', 'package bounds', 'type errors'], ['fix cabal/stack config', 'repair modules', 'stabilize build']),
  expert('ocaml', 'OCaml Expert Agent', 'language', 'ocaml/ocaml', ['https://ocaml.org/docs', 'https://github.com/ocaml/ocaml/releases'], ['dune-project', 'dune', '**/*.ml', '**/*.mli'], ['ocaml', 'dune', 'opam'], ['Dune config', 'opam deps', 'module errors'], ['fix dune files', 'repair opam config', 'stabilize build']),
  expert('perl', 'Perl Expert Agent', 'language', 'Perl/perl5', ['https://perldoc.perl.org/', 'https://github.com/Perl/perl5'], ['cpanfile', 'Makefile.PL', '**/*.pl', '**/*.pm'], ['perl', 'cpanm'], ['module paths', 'CPAN deps', 'runtime warnings'], ['fix cpanfile', 'repair package paths', 'stabilize tests']),
  expert('powershell', 'PowerShell Expert Agent', 'language', 'PowerShell/PowerShell', ['https://learn.microsoft.com/powershell/', 'https://github.com/PowerShell/PowerShell/releases'], ['**/*.ps1', '**/*.psm1'], ['powershell'], ['execution policy', 'module imports', 'cross-platform behavior'], ['fix scripts', 'repair module paths', 'add safe invocation guidance']),
  expert('bash', 'Bash/Shell Expert Agent', 'language', 'bminor/bash', ['https://www.gnu.org/software/bash/manual/', 'https://github.com/bminor/bash'], ['**/*.sh', 'Makefile'], ['bash', 'shellcheck'], ['POSIX/Bash syntax', 'quoting', 'exit handling'], ['fix shell scripts', 'repair quoting', 'add safe flags']),
  expert('mssql', 'SQL Server Expert Agent', 'database', 'microsoft/mssql-server-linux', ['https://learn.microsoft.com/sql/sql-server/', 'https://github.com/microsoft/mssql-server-linux'], ['**/*.sql', 'docker-compose.yml'], ['mssql', 'tedious'], ['T-SQL dialect', 'connection strings', 'migration scripts'], ['fix SQL Server schema', 'repair connection env', 'document setup']),
  expert('mariadb', 'MariaDB Expert Agent', 'database', 'MariaDB/server', ['https://mariadb.com/kb/en/documentation/', 'https://github.com/MariaDB/server'], ['**/*.sql', 'docker-compose.yml'], ['mariadb'], ['MariaDB dialect', 'storage engines', 'connection env'], ['repair schema', 'fix queries', 'document env vars']),
  expert('cassandra', 'Cassandra Expert Agent', 'database', 'apache/cassandra', ['https://cassandra.apache.org/doc/latest/', 'https://github.com/apache/cassandra'], ['**/*.cql', 'docker-compose.yml'], ['cassandra-driver'], ['CQL schema', 'partition keys', 'cluster config'], ['fix CQL schema', 'repair driver config', 'document cluster env']),
  expert('neo4j', 'Neo4j Expert Agent', 'database', 'neo4j/neo4j', ['https://neo4j.com/docs/', 'https://github.com/neo4j/neo4j'], ['**/*.cypher', 'src/**/*.{ts,js,py}'], ['neo4j-driver'], ['Cypher queries', 'driver config', 'indexes/constraints'], ['fix Cypher', 'repair driver setup', 'add constraints']),
  expert('clickhouse', 'ClickHouse Expert Agent', 'database', 'ClickHouse/ClickHouse', ['https://clickhouse.com/docs', 'https://github.com/ClickHouse/ClickHouse/releases'], ['**/*.sql', 'docker-compose.yml'], ['@clickhouse/client', 'clickhouse'], ['MergeTree schema', 'analytics queries', 'connection env'], ['fix table engines', 'repair queries', 'document setup']),
  expert('duckdb', 'DuckDB Expert Agent', 'database', 'duckdb/duckdb', ['https://duckdb.org/docs/', 'https://github.com/duckdb/duckdb/releases'], ['**/*.sql', '**/*.duckdb'], ['duckdb'], ['local analytics schema', 'file paths', 'extensions'], ['fix DuckDB SQL', 'repair local file usage', 'document extensions']),
  expert('elasticsearch', 'Elasticsearch Expert Agent', 'search', 'elastic/elasticsearch', ['https://www.elastic.co/docs', 'https://github.com/elastic/elasticsearch/releases'], ['src/**/*.{ts,js,py}', 'docker-compose.yml'], ['@elastic/elasticsearch'], ['index mappings', 'queries', 'connection auth'], ['fix mappings', 'repair client setup', 'document auth/env']),
  expert('opensearch', 'OpenSearch Expert Agent', 'search', 'opensearch-project/OpenSearch', ['https://opensearch.org/docs/', 'https://github.com/opensearch-project/OpenSearch/releases'], ['src/**/*.{ts,js,py}', 'docker-compose.yml'], ['@opensearch-project/opensearch'], ['index mappings', 'queries', 'cluster config'], ['fix mappings', 'repair client setup', 'document cluster env']),
  expert('meilisearch', 'Meilisearch Expert Agent', 'search', 'meilisearch/meilisearch', ['https://www.meilisearch.com/docs', 'https://github.com/meilisearch/meilisearch/releases'], ['src/**/*.{ts,js,py}', 'docker-compose.yml'], ['meilisearch'], ['index schema', 'search keys', 'sync jobs'], ['fix client setup', 'repair index config', 'document API keys']),
  expert('supabase', 'Supabase Expert Agent', 'database-service', 'supabase/supabase', ['https://supabase.com/docs', 'https://github.com/supabase/supabase/releases'], ['supabase/**', '.env.example', 'src/**/*.{ts,tsx,js}'], ['@supabase/supabase-js'], ['project URL/keys', 'RLS policies', 'auth/database/storage'], ['fix Supabase client', 'repair RLS guidance', 'document env vars']),
  expert('firebase', 'Firebase Expert Agent', 'database-service', 'firebase/firebase-js-sdk', ['https://firebase.google.com/docs', 'https://github.com/firebase/firebase-js-sdk/releases'], ['firebase.json', 'src/**/*.{ts,tsx,js}'], ['firebase'], ['project config', 'Firestore rules', 'auth/storage env'], ['fix Firebase init', 'repair rules guidance', 'document env vars']),
  expert('neon', 'Neon Postgres Expert Agent', 'database-service', 'neondatabase/serverless', ['https://neon.com/docs', 'https://github.com/neondatabase/serverless/releases'], ['.env.example', 'src/**/*.{ts,js}', 'schema.prisma'], ['@neondatabase/serverless'], ['serverless Postgres URL', 'pooling', 'Prisma/Drizzle driver'], ['fix Neon client', 'repair DATABASE_URL docs', 'align ORM adapter']),
  expert('planetscale', 'PlanetScale Expert Agent', 'database-service', 'planetscale/cli', ['https://planetscale.com/docs', 'https://github.com/planetscale/cli/releases'], ['.env.example', 'schema.prisma', 'drizzle.config.*'], ['@planetscale/database'], ['branching workflow', 'connection URL', 'schema migrations'], ['fix PlanetScale client', 'repair migration workflow', 'document env vars']),
  expert('turso', 'Turso/libSQL Expert Agent', 'database-service', 'tursodatabase/libsql', ['https://docs.turso.tech/', 'https://github.com/tursodatabase/libsql/releases'], ['.env.example', 'src/**/*.{ts,js}', '**/*.sql'], ['@libsql/client'], ['database URL/token', 'local replica', 'SQLite compatibility'], ['fix libSQL client', 'repair token env', 'document local/cloud setup']),
  expert('mongodb-atlas', 'MongoDB Atlas Expert Agent', 'database-service', 'mongodb/node-mongodb-native', ['https://www.mongodb.com/docs/atlas/', 'https://github.com/mongodb/node-mongodb-native/releases'], ['.env.example', 'src/**/*.{ts,js}'], ['mongodb', 'mongoose'], ['Atlas URI', 'IP allowlist assumptions', 'indexes'], ['fix Atlas connection', 'repair model config', 'document env/security']),
  expert('upstash', 'Upstash Redis Expert Agent', 'database-service', 'upstash/redis-js', ['https://upstash.com/docs/redis', 'https://github.com/upstash/redis-js/releases'], ['.env.example', 'src/**/*.{ts,js}'], ['@upstash/redis'], ['REST token/url', 'rate limits', 'cache TTL'], ['fix Upstash client', 'repair env docs', 'add cache fallbacks']),
  expert('aws-rds', 'AWS RDS Expert Agent', 'database-service', 'aws/aws-sdk-js-v3', ['https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html', 'https://github.com/aws/aws-sdk-js-v3/releases'], ['.env.example', 'src/**/*.{ts,js}', 'terraform/**'], ['@aws-sdk/client-rds'], ['RDS endpoint/env', 'security groups', 'migrations'], ['document RDS env', 'repair connection config', 'add deployment guidance']),
  expert('google-cloud-sql', 'Google Cloud SQL Expert Agent', 'database-service', 'googleapis/google-cloud-node', ['https://cloud.google.com/sql/docs', 'https://github.com/googleapis/google-cloud-node/releases'], ['.env.example', 'src/**/*.{ts,js}', 'terraform/**'], ['@google-cloud/cloud-sql-connector'], ['Cloud SQL connector', 'IAM/env', 'migration path'], ['fix connector config', 'document env/IAM', 'repair database URL']),
  expert('azure-sql', 'Azure SQL Expert Agent', 'database-service', 'Azure/azure-sdk-for-js', ['https://learn.microsoft.com/azure/azure-sql/', 'https://github.com/Azure/azure-sdk-for-js/releases'], ['.env.example', 'src/**/*.{ts,js}', 'terraform/**'], ['@azure/identity', 'mssql'], ['connection strings', 'managed identity', 'firewall rules'], ['repair connection config', 'document Azure env', 'add safe auth guidance']),
  expert('rest', 'REST API Expert Agent', 'protocol', 'microsoft/api-guidelines', ['https://github.com/microsoft/api-guidelines', 'https://restfulapi.net/'], ['openapi.*', 'src/**/*.{ts,js,py,go,cs,java}'], ['express', 'fastapi', 'openapi'], ['resources/methods', 'status codes', 'pagination', 'idempotency'], ['repair REST routes', 'standardize errors', 'document endpoints']),
  expert('jwt', 'JWT Expert Agent', 'security', 'panva/jose', ['https://datatracker.ietf.org/doc/html/rfc7519', 'https://github.com/panva/jose/releases'], ['src/**/*.{ts,js}', '.env.example'], ['jose', 'jsonwebtoken'], ['issuer/audience', 'expiration', 'signature algorithm', 'secret handling'], ['fix token validation', 'repair env secrets', 'avoid insecure decode-only auth']),
  expert('oauth2', 'OAuth 2.0 Expert Agent', 'auth', 'panva/openid-client', ['https://oauth.net/2/', 'https://github.com/panva/openid-client/releases'], ['src/**/*.{ts,js}', '.env.example'], ['openid-client', 'next-auth', '@auth/core'], ['redirect URIs', 'PKCE', 'scopes', 'client secrets'], ['fix OAuth flow', 'repair callback routes', 'document provider env']),
  expert('openid-connect', 'OpenID Connect Expert Agent', 'auth', 'openid/AppAuth-JS', ['https://openid.net/developers/how-connect-works/', 'https://github.com/openid/AppAuth-JS'], ['src/**/*.{ts,js}', '.env.example'], ['openid-client', 'jose'], ['ID token validation', 'discovery docs', 'nonce/state'], ['repair OIDC config', 'validate tokens safely', 'document scopes']),
  expert('cors', 'CORS Expert Agent', 'security', 'expressjs/cors', ['https://developer.mozilla.org/docs/Web/HTTP/CORS', 'https://github.com/expressjs/cors'], ['server.*', 'src/**/*.{ts,js,py}'], ['cors'], ['origins', 'credentials', 'preflight', 'headers'], ['fix CORS middleware', 'avoid wildcard credentials', 'document origins']),
  expert('websocket', 'WebSocket Expert Agent', 'protocol', 'websockets/ws', ['https://developer.mozilla.org/docs/Web/API/WebSockets_API', 'https://github.com/websockets/ws/releases'], ['src/**/*.{ts,js}', 'server.*'], ['ws', 'socket.io'], ['connection lifecycle', 'heartbeats', 'auth', 'message schemas'], ['fix socket lifecycle', 'repair auth/heartbeat', 'document events']),
  expert('grpc', 'gRPC Expert Agent', 'protocol', 'grpc/grpc', ['https://grpc.io/docs/', 'https://github.com/grpc/grpc/releases'], ['**/*.proto', 'src/**/*.{ts,js,go,py,java}'], ['@grpc/grpc-js', 'grpc'], ['proto contracts', 'codegen', 'deadlines', 'metadata auth'], ['fix proto/codegen', 'repair client/server wiring', 'document calls']),
  expert('trpc', 'tRPC Expert Agent', 'api', 'trpc/trpc', ['https://trpc.io/docs', 'https://github.com/trpc/trpc/releases'], ['src/**/*.{ts,tsx}', 'server/**/*.{ts,tsx}'], ['@trpc/server', '@trpc/client'], ['router types', 'procedure context', 'client provider'], ['fix router/client types', 'repair context', 'stabilize end-to-end types']),
  expert('webhooks', 'Webhooks Expert Agent', 'api', 'standard-webhooks/standard-webhooks', ['https://github.com/standard-webhooks/standard-webhooks', 'https://docs.stripe.com/webhooks'], ['src/**/*.{ts,js,py}', '.env.example'], ['stripe', 'svix'], ['signature verification', 'raw body', 'idempotency', 'retries'], ['fix webhook routes', 'repair signature validation', 'add idempotency handling']),
  expert('http', 'HTTP Expert Agent', 'protocol', 'httpwg/http-core', ['https://httpwg.org/specs/', 'https://github.com/httpwg/http-core'], ['src/**/*.{ts,js,py,go}', 'openapi.*'], ['fetch', 'axios', 'undici'], ['methods', 'headers', 'cache-control', 'status semantics'], ['repair HTTP clients', 'standardize errors', 'add retry/cache policy']),
  expert('aws', 'AWS Expert Agent', 'cloud', 'aws/aws-sdk-js-v3', ['https://docs.aws.amazon.com/', 'https://github.com/aws/aws-sdk-js-v3/releases'], ['.env.example', 'terraform/**', 'serverless.*'], ['@aws-sdk/*'], ['IAM/env', 'regions', 'service clients', 'least privilege'], ['fix AWS clients', 'document IAM/env', 'repair deployment config']),
  expert('gcp', 'Google Cloud Expert Agent', 'cloud', 'googleapis/google-cloud-node', ['https://cloud.google.com/docs', 'https://github.com/googleapis/google-cloud-node/releases'], ['.env.example', 'terraform/**', 'cloudbuild.yaml'], ['@google-cloud/*'], ['service accounts', 'project IDs', 'regions', 'IAM'], ['fix GCP clients', 'document IAM/env', 'repair deploy config']),
  expert('azure', 'Azure Expert Agent', 'cloud', 'Azure/azure-sdk-for-js', ['https://learn.microsoft.com/azure/', 'https://github.com/Azure/azure-sdk-for-js/releases'], ['.env.example', 'terraform/**'], ['@azure/*'], ['tenant/client IDs', 'managed identity', 'regions'], ['fix Azure clients', 'document identity/env', 'repair deployment config']),
  expert('s3', 'S3 Storage Expert Agent', 'storage', 'aws/aws-sdk-js-v3', ['https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html', 'https://github.com/aws/aws-sdk-js-v3/releases'], ['src/**/*.{ts,js}', '.env.example'], ['@aws-sdk/client-s3'], ['bucket/region env', 'signed URLs', 'CORS', 'permissions'], ['fix S3 client', 'repair signed uploads', 'document bucket policy']),
  expert('cloudflare-r2', 'Cloudflare R2 Expert Agent', 'storage', 'cloudflare/workers-sdk', ['https://developers.cloudflare.com/r2/', 'https://github.com/cloudflare/workers-sdk/releases'], ['wrangler.toml', 'src/**/*.{ts,js}'], ['wrangler', '@aws-sdk/client-s3'], ['R2 bindings', 'S3-compatible config', 'tokens'], ['fix R2 binding/client', 'repair env docs', 'document uploads']),
  expert('rabbitmq', 'RabbitMQ Expert Agent', 'message-queue', 'rabbitmq/rabbitmq-server', ['https://www.rabbitmq.com/docs', 'https://github.com/rabbitmq/rabbitmq-server/releases'], ['docker-compose.yml', 'src/**/*.{ts,js,py}'], ['amqplib', 'aio-pika'], ['exchanges/queues', 'acks', 'retries', 'DLQ'], ['fix queue topology', 'repair consumers', 'document retry policy']),
  expert('kafka', 'Kafka Expert Agent', 'message-queue', 'apache/kafka', ['https://kafka.apache.org/documentation/', 'https://github.com/apache/kafka/releases'], ['docker-compose.yml', 'src/**/*.{ts,js,py,java}'], ['kafkajs', 'kafka-python'], ['topics', 'consumer groups', 'offsets', 'brokers'], ['fix producer/consumer config', 'repair topic setup', 'document env vars']),
  expert('bullmq', 'BullMQ Expert Agent', 'message-queue', 'taskforcesh/bullmq', ['https://docs.bullmq.io/', 'https://github.com/taskforcesh/bullmq/releases'], ['src/**/*.{ts,js}', '.env.example'], ['bullmq', 'ioredis'], ['Redis connection', 'workers', 'retries', 'job schemas'], ['fix worker setup', 'repair queue config', 'document Redis env']),
  expert('turbo', 'Turborepo Expert Agent', 'monorepo', 'vercel/turborepo', ['https://turbo.build/repo/docs', 'https://github.com/vercel/turborepo/releases'], ['turbo.json', 'package.json', 'packages/**'], ['turbo'], ['pipeline tasks', 'workspace deps', 'cache config'], ['fix turbo pipeline', 'repair workspace scripts', 'stabilize builds']),
  expert('nx', 'Nx Expert Agent', 'monorepo', 'nrwl/nx', ['https://nx.dev/docs', 'https://github.com/nrwl/nx/releases'], ['nx.json', 'project.json', 'workspace.json'], ['nx'], ['project graph', 'targets', 'generators', 'cache'], ['fix Nx targets', 'repair project config', 'stabilize affected builds']),
  expert('rush', 'Rush Expert Agent', 'monorepo', 'microsoft/rushstack', ['https://rushjs.io/', 'https://github.com/microsoft/rushstack/releases'], ['rush.json', 'common/config/rush/**'], ['@microsoft/rush'], ['rush config', 'package policies', 'versioning'], ['fix rush config', 'repair package policies', 'stabilize install/build']),
  expert('pypi', 'PyPI Packaging Expert Agent', 'package-registry', 'pypa/warehouse', ['https://packaging.python.org/', 'https://github.com/pypi/warehouse'], ['pyproject.toml', 'setup.py', 'setup.cfg'], ['build', 'twine', 'hatch', 'poetry'], ['metadata', 'wheels/sdist', 'versioning', 'publish config'], ['fix package metadata', 'repair build backend', 'document publish flow']),
  expert('composer', 'Composer Expert Agent', 'package-manager', 'composer/composer', ['https://getcomposer.org/doc/', 'https://github.com/composer/composer/releases'], ['composer.json', 'composer.lock'], ['composer'], ['autoload', 'platform PHP', 'dependency constraints'], ['fix composer.json', 'repair autoload', 'stabilize install']),
  expert('maven', 'Maven Expert Agent', 'package-manager', 'apache/maven', ['https://maven.apache.org/guides/', 'https://github.com/apache/maven/releases'], ['pom.xml'], ['maven'], ['plugins', 'dependency scopes', 'Java target'], ['fix pom.xml', 'repair plugin config', 'stabilize mvn test/package']),
  expert('gradle', 'Gradle Expert Agent', 'package-manager', 'gradle/gradle', ['https://docs.gradle.org/current/userguide/userguide.html', 'https://github.com/gradle/gradle/releases'], ['build.gradle', 'build.gradle.kts', 'settings.gradle*'], ['gradle'], ['plugins', 'source sets', 'dependency configuration'], ['fix Gradle config', 'repair plugins', 'stabilize build']),
  expert('cargo', 'Cargo Expert Agent', 'package-manager', 'rust-lang/cargo', ['https://doc.rust-lang.org/cargo/', 'https://github.com/rust-lang/cargo/releases'], ['Cargo.toml', 'Cargo.lock'], ['cargo'], ['features', 'workspace config', 'crate versions'], ['fix Cargo manifest', 'repair features', 'stabilize cargo test/build']),
  expert('huggingface', 'Hugging Face Expert Agent', 'ai', 'huggingface/transformers', ['https://huggingface.co/docs', 'https://github.com/huggingface/transformers/releases'], ['src/**/*.{py,ts,js}', '.env.example'], ['transformers', '@huggingface/inference'], ['model IDs', 'token env', 'inference APIs'], ['fix HF client setup', 'repair model config', 'document token env']),
  expert('langchain', 'LangChain Expert Agent', 'ai', 'langchain-ai/langchainjs', ['https://js.langchain.com/docs/', 'https://github.com/langchain-ai/langchainjs/releases'], ['src/**/*.{ts,js,py}', '.env.example'], ['langchain', '@langchain/core'], ['model providers', 'tools', 'chains/agents', 'env keys'], ['fix LangChain setup', 'repair tools', 'document provider env']),
  expert('mcp', 'MCP Expert Agent', 'api', 'modelcontextprotocol/typescript-sdk', ['https://modelcontextprotocol.io/', 'https://github.com/modelcontextprotocol/typescript-sdk/releases'], ['mcp/**', 'src/**/*.{ts,js}', 'opencode*.json'], ['@modelcontextprotocol/sdk'], ['tool schemas', 'server transport', 'permissions', 'env secrets'], ['fix MCP server', 'repair tool schemas', 'document client config']),
  expert('wordpress', 'WordPress Expert Agent', 'cms', 'WordPress/wordpress-develop', ['https://developer.wordpress.org/', 'https://github.com/WordPress/wordpress-develop'], ['wp-config.php', 'wp-content/**', '**/*.php'], ['wordpress'], ['plugin/theme structure', 'hooks', 'REST API', 'security nonces'], ['fix plugin/theme files', 'repair hooks', 'document setup']),
  expert('strapi', 'Strapi Expert Agent', 'cms', 'strapi/strapi', ['https://docs.strapi.io/', 'https://github.com/strapi/strapi/releases'], ['config/**', 'src/api/**', 'package.json'], ['@strapi/strapi'], ['content types', 'permissions', 'database config'], ['fix Strapi config', 'repair content types', 'document env vars']),
  expert('contentful', 'Contentful Expert Agent', 'cms', 'contentful/contentful.js', ['https://www.contentful.com/developers/docs/', 'https://github.com/contentful/contentful.js/releases'], ['src/**/*.{ts,js}', '.env.example'], ['contentful'], ['space/env/access tokens', 'content models', 'preview API'], ['fix Contentful client', 'repair env docs', 'add preview fallback']),
  expert('dynamodb', 'DynamoDB Expert Agent', 'database-service', 'aws/aws-sdk-js-v3', ['https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html', 'https://github.com/aws/aws-sdk-js-v3/releases'], ['src/**/*.{ts,js}', '.env.example', 'terraform/**'], ['@aws-sdk/client-dynamodb', '@aws-sdk/lib-dynamodb'], ['partition/sort keys', 'GSI/LSI design', 'IAM/env', 'capacity mode'], ['fix DynamoDB client', 'repair key schema', 'document IAM/env']),
  expert('firestore', 'Firestore Expert Agent', 'database-service', 'firebase/firebase-js-sdk', ['https://firebase.google.com/docs/firestore', 'https://github.com/firebase/firebase-js-sdk/releases'], ['firebase.json', 'src/**/*.{ts,js,tsx}'], ['firebase', '@google-cloud/firestore'], ['collection paths', 'security rules', 'indexes', 'offline/cache'], ['fix Firestore client', 'repair security rules guidance', 'document indexes/env']),
  expert('cockroachdb', 'CockroachDB Expert Agent', 'database-service', 'cockroachdb/cockroach', ['https://www.cockroachlabs.com/docs/', 'https://github.com/cockroachdb/cockroach/releases'], ['**/*.sql', 'schema.prisma', 'drizzle.config.*'], ['pg', 'postgres'], ['Postgres compatibility', 'serializable retries', 'connection URL'], ['fix Cockroach SQL', 'add retry guidance', 'document connection env']),
  expert('timescaledb', 'TimescaleDB Expert Agent', 'database-service', 'timescale/timescaledb', ['https://docs.timescale.com/', 'https://github.com/timescale/timescaledb/releases'], ['**/*.sql', 'schema.prisma'], ['pg', 'postgres'], ['hypertables', 'time indexes', 'retention/compression'], ['fix hypertable schema', 'repair time-series queries', 'document extension setup']),
  expert('fauna', 'Fauna Expert Agent', 'database-service', 'fauna/fauna-js', ['https://docs.fauna.com/', 'https://github.com/fauna/fauna-js/releases'], ['src/**/*.{ts,js}', '.env.example'], ['fauna'], ['secret env', 'schema/query model', 'driver version'], ['fix Fauna client', 'repair query setup', 'document secrets']),
  expert('hasura', 'Hasura Expert Agent', 'database-service', 'hasura/graphql-engine', ['https://hasura.io/docs/', 'https://github.com/hasura/graphql-engine/releases'], ['metadata/**', 'migrations/**', 'docker-compose.yml'], ['hasura-cli'], ['metadata', 'migrations', 'permissions', 'GraphQL schema'], ['fix metadata', 'repair permissions', 'document env/admin secret']),
  expert('appwrite', 'Appwrite Expert Agent', 'database-service', 'appwrite/appwrite', ['https://appwrite.io/docs', 'https://github.com/appwrite/appwrite/releases'], ['src/**/*.{ts,js,tsx}', '.env.example'], ['appwrite'], ['project endpoint/id', 'auth/database/storage permissions'], ['fix Appwrite client', 'repair permissions guidance', 'document env vars']),
  expert('pocketbase', 'PocketBase Expert Agent', 'database-service', 'pocketbase/pocketbase', ['https://pocketbase.io/docs/', 'https://github.com/pocketbase/pocketbase/releases'], ['pb_schema.json', 'src/**/*.{ts,js}'], ['pocketbase'], ['collections', 'rules', 'auth stores', 'file storage'], ['fix PocketBase client', 'repair rules guidance', 'document local/server setup']),
  expert('asyncapi', 'AsyncAPI Expert Agent', 'api', 'asyncapi/spec', ['https://www.asyncapi.com/docs', 'https://github.com/asyncapi/spec'], ['asyncapi.yaml', 'asyncapi.json'], ['@asyncapi/parser'], ['channels', 'messages', 'bindings', 'server definitions'], ['repair AsyncAPI spec', 'generate event clients', 'document brokers']),
  expert('soap', 'SOAP/WSDL Expert Agent', 'protocol', 'apache/cxf', ['https://www.w3.org/TR/wsdl20/', 'https://github.com/apache/cxf'], ['**/*.wsdl', 'src/**/*.{ts,js,java,cs,php}'], ['soap', 'strong-soap'], ['WSDL contracts', 'XML namespaces', 'SOAP actions', 'client generation'], ['fix SOAP client', 'repair XML namespaces', 'document endpoint/auth']),
  expert('xml', 'XML/XSD Expert Agent', 'protocol', 'GNOME/libxml2', ['https://www.w3.org/XML/', 'https://github.com/GNOME/libxml2'], ['**/*.xml', '**/*.xsd'], ['xml2js', 'fast-xml-parser'], ['schema validation', 'namespaces', 'encoding'], ['repair XML parsing', 'fix namespace handling', 'document schema assumptions']),
  expert('json-schema', 'JSON Schema Expert Agent', 'api', 'json-schema-org/json-schema-spec', ['https://json-schema.org/learn', 'https://github.com/json-schema-org/json-schema-spec'], ['**/*.schema.json', 'openapi.*'], ['ajv', 'zod'], ['schema draft', 'validation errors', 'nullable/required fields'], ['repair schemas', 'align validators', 'generate safe types']),
  expert('zod', 'Zod Expert Agent', 'api', 'colinhacks/zod', ['https://zod.dev/', 'https://github.com/colinhacks/zod/releases'], ['src/**/*.{ts,tsx}'], ['zod'], ['runtime validation', 'inferred types', 'env schemas', 'API contracts'], ['fix Zod schemas', 'repair env validation', 'align API types']),
  expert('cookie-session', 'Cookie/Session Expert Agent', 'security', 'expressjs/session', ['https://developer.mozilla.org/docs/Web/HTTP/Cookies', 'https://github.com/expressjs/session'], ['server.*', 'src/**/*.{ts,js}', '.env.example'], ['express-session', 'cookie'], ['secure/httpOnly/sameSite flags', 'session secret', 'store config'], ['fix cookie flags', 'repair session storage', 'document secrets']),
  expert('saml', 'SAML Expert Agent', 'auth', 'node-saml/node-saml', ['https://docs.oasis-open.org/security/saml/v2.0/', 'https://github.com/node-saml/node-saml/releases'], ['src/**/*.{ts,js}', '.env.example'], ['@node-saml/node-saml', 'passport-saml'], ['metadata', 'certificates', 'ACS URL', 'issuer/audience'], ['fix SAML config', 'repair certificate env', 'document IdP setup']),
  expert('rate-limit', 'Rate Limit Expert Agent', 'security', 'express-rate-limit/express-rate-limit', ['https://github.com/express-rate-limit/express-rate-limit', 'https://developer.mozilla.org/docs/Web/HTTP/Status/429'], ['server.*', 'src/**/*.{ts,js}'], ['express-rate-limit', '@upstash/ratelimit'], ['429 behavior', 'identity keys', 'distributed store', 'Retry-After'], ['fix rate limiting', 'repair store config', 'document abuse controls']),
  expert('csrf', 'CSRF Expert Agent', 'security', 'expressjs/csurf', ['https://owasp.org/www-community/attacks/csrf', 'https://github.com/expressjs/csurf'], ['server.*', 'src/**/*.{ts,js,tsx}'], ['csrf', 'csurf'], ['same-site cookies', 'token generation', 'unsafe methods'], ['fix CSRF protection', 'repair form tokens', 'document security tradeoffs']),
  expert('owasp', 'OWASP AppSec Expert Agent', 'security', 'OWASP/Top10', ['https://owasp.org/www-project-top-ten/', 'https://github.com/OWASP/Top10'], ['src/**/*', 'server.*', '.env.example'], ['helmet', 'zod', 'jose'], ['injection', 'auth failures', 'secrets exposure', 'XSS', 'SSRF'], ['add validation', 'repair auth boundaries', 'harden headers', 'redact secrets']),
  expert('swagger-ui', 'Swagger UI Expert Agent', 'api', 'swagger-api/swagger-ui', ['https://swagger.io/docs/open-source-tools/swagger-ui/usage/installation/', 'https://github.com/swagger-api/swagger-ui/releases'], ['openapi.*', 'src/**/*.{ts,js}'], ['swagger-ui-express', 'swagger-ui-react'], ['OpenAPI rendering', 'server URLs', 'auth schemes'], ['fix docs route', 'repair spec rendering', 'document auth']),
  expert('postman', 'Postman Collection Expert Agent', 'api', 'postmanlabs/postman-collection', ['https://learning.postman.com/docs/', 'https://github.com/postmanlabs/postman-collection'], ['*.postman_collection.json', 'openapi.*'], ['postman-collection'], ['collection variables', 'auth setup', 'test scripts'], ['repair collections', 'generate examples', 'document environments']),
  expert('insomnia', 'Insomnia API Client Expert Agent', 'api', 'Kong/insomnia', ['https://docs.insomnia.rest/', 'https://github.com/Kong/insomnia/releases'], ['insomnia*.json', 'openapi.*'], ['insomnia'], ['workspace export', 'env variables', 'request auth'], ['repair request collections', 'document environments', 'align OpenAPI import']),
  expert('nginx', 'Nginx Expert Agent', 'devops', 'nginx/nginx', ['https://nginx.org/en/docs/', 'https://github.com/nginx/nginx'], ['nginx.conf', 'conf.d/*.conf', 'docker-compose.yml'], ['nginx'], ['reverse proxy', 'static assets', 'TLS', 'headers'], ['fix proxy config', 'repair static routing', 'document TLS/env']),
  expert('caddy', 'Caddy Expert Agent', 'devops', 'caddyserver/caddy', ['https://caddyserver.com/docs/', 'https://github.com/caddyserver/caddy/releases'], ['Caddyfile', 'docker-compose.yml'], ['caddy'], ['reverse proxy', 'automatic HTTPS', 'headers'], ['fix Caddyfile', 'repair proxy routes', 'document deployment']),
  expert('prometheus', 'Prometheus Expert Agent', 'observability', 'prometheus/prometheus', ['https://prometheus.io/docs/', 'https://github.com/prometheus/prometheus/releases'], ['prometheus.yml', 'src/**/*.{ts,js,go,py}'], ['prom-client', 'prometheus'], ['metrics endpoints', 'scrape config', 'labels/cardinality'], ['fix metrics route', 'repair scrape config', 'document dashboards']),
  expert('opentelemetry', 'OpenTelemetry Expert Agent', 'observability', 'open-telemetry/opentelemetry-js', ['https://opentelemetry.io/docs/', 'https://github.com/open-telemetry/opentelemetry-js/releases'], ['src/**/*.{ts,js}', 'otel.*'], ['@opentelemetry/*'], ['tracing setup', 'exporters', 'resource attributes'], ['fix OTEL setup', 'repair exporters', 'document observability env']),
  expert('sso', 'SSO Architecture Expert Agent', 'auth', 'panva/openid-client', ['https://openid.net/connect/', 'https://github.com/panva/openid-client/releases', 'https://docs.oasis-open.org/security/saml/v2.0/'], ['src/**/*.{ts,js}', 'middleware.*', '.env.example'], ['openid-client', 'next-auth', '@auth/core', '@node-saml/node-saml'], ['SSO provider config', 'OIDC vs SAML choice', 'redirect URLs', 'claims/roles mapping', 'tenant/domain routing'], ['repair SSO config', 'document provider setup', 'fix callback/session mapping', 'protect routes safely']),
  expert('soc2', 'SOC 2 Readiness Expert Agent', 'compliance', 'strongdm/comply', ['https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services', 'https://github.com/strongdm/comply'], ['README.md', 'docs/**', 'src/**/*', '.github/workflows/**'], ['sentry', 'opentelemetry', 'eslint', 'playwright'], ['audit logs', 'access controls', 'change management', 'incident response', 'vendor/security docs'], ['add audit log guidance', 'document access controls', 'add security checklist', 'create compliance evidence map']),
  expert('gdpr', 'GDPR Privacy Expert Agent', 'compliance', 'privacycg/storage-access', ['https://gdpr.eu/', 'https://github.com/privacycg/storage-access'], ['src/**/*.{ts,tsx,js,jsx}', 'privacy*', 'cookie*'], ['cookie', 'analytics', 'posthog'], ['consent flows', 'data export/delete', 'PII minimization', 'cookie categories'], ['add consent controls', 'document PII handling', 'repair analytics privacy mode', 'add deletion/export guidance']),
  expert('hipaa', 'HIPAA Safeguards Expert Agent', 'compliance', 'HHS/Grants-Management-System', ['https://www.hhs.gov/hipaa/for-professionals/security/index.html', 'https://github.com/HHS/Grants-Management-System'], ['src/**/*', 'docs/**', '.env.example'], ['helmet', 'sentry', 'opentelemetry'], ['PHI handling', 'audit controls', 'access controls', 'encryption notes'], ['add PHI warnings', 'document safeguards', 'repair logging redaction', 'add access-control checklist']),
  expert('boilerplates', 'Boilerplate Selection Expert Agent', 'boilerplate', 'vercel/next.js', ['https://vercel.com/templates', 'https://github.com/vercel/next.js/tree/canary/examples', 'https://github.com/vitejs/vite/tree/main/packages/create-vite'], ['package.json', 'src/**', 'app/**', 'pages/**'], ['create-vite', 'next', 'tailwindcss'], ['template fit', 'routing model', 'database/auth/payment needs', 'deployment target'], ['select starter architecture', 'repair generated file layout', 'add missing baseline scripts', 'document chosen stack']),
  expert('create-t3-app', 'T3 Stack Boilerplate Expert Agent', 'boilerplate', 't3-oss/create-t3-app', ['https://create.t3.gg/', 'https://github.com/t3-oss/create-t3-app/releases'], ['package.json', 'src/**', 'prisma/**'], ['create-t3-app', 'next', 'trpc', 'prisma'], ['T3 stack fit', 'env validation', 'tRPC/Prisma/Auth wiring'], ['repair T3 setup', 'fix env schema', 'align app router choices']),
  expert('shadcn-ui', 'shadcn/ui Expert Agent', 'design-system', 'shadcn-ui/ui', ['https://ui.shadcn.com/docs', 'https://github.com/shadcn-ui/ui'], ['components.json', 'src/components/**', 'tailwind.config.*'], ['class-variance-authority', 'radix-ui', 'tailwindcss'], ['component registry', 'Tailwind variables', 'Radix composition', 'theme tokens'], ['repair shadcn setup', 'fix component imports', 'align CSS variables', 'add accessible variants']),
  expert('radix-ui', 'Radix UI Expert Agent', 'design-system', 'radix-ui/primitives', ['https://www.radix-ui.com/primitives/docs/overview/introduction', 'https://github.com/radix-ui/primitives/releases'], ['src/components/**/*.{ts,tsx}'], ['@radix-ui/react-dialog', '@radix-ui/react-dropdown-menu'], ['ARIA patterns', 'controlled state', 'portals', 'focus management'], ['fix accessible primitives', 'repair focus traps', 'wire controlled state safely']),
  expert('material-ui', 'Material UI Expert Agent', 'design-system', 'mui/material-ui', ['https://mui.com/material-ui/getting-started/', 'https://github.com/mui/material-ui/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['@mui/material', '@emotion/react'], ['theme provider', 'emotion setup', 'SSR styles', 'component variants'], ['fix MUI theme', 'repair imports', 'stabilize SSR styling']),
  expert('chakra-ui', 'Chakra UI Expert Agent', 'design-system', 'chakra-ui/chakra-ui', ['https://chakra-ui.com/docs', 'https://github.com/chakra-ui/chakra-ui/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['@chakra-ui/react'], ['provider setup', 'theme tokens', 'accessibility props'], ['fix Chakra provider', 'repair theme config', 'align component props']),
  expert('css', 'Modern CSS Expert Agent', 'frontend', 'w3c/csswg-drafts', ['https://developer.mozilla.org/docs/Web/CSS', 'https://github.com/w3c/csswg-drafts'], ['src/**/*.css', 'src/**/*.{tsx,jsx,html}', 'public/**/*.css'], ['postcss', 'autoprefixer'], ['cascade layers', 'container queries', 'logical properties', 'responsive layout', 'browser support'], ['repair CSS layout', 'fix cascade conflicts', 'add responsive/container-query patterns', 'reduce brittle overrides']),
  expert('sass', 'Sass Expert Agent', 'frontend', 'sass/dart-sass', ['https://sass-lang.com/documentation/', 'https://github.com/sass/dart-sass/releases'], ['**/*.scss', '**/*.sass'], ['sass'], ['module syntax', 'variables/mixins', 'build integration'], ['fix Sass imports', 'repair build config', 'modernize @use/@forward']),
  expert('postcss', 'PostCSS Expert Agent', 'build-tool', 'postcss/postcss', ['https://postcss.org/', 'https://github.com/postcss/postcss/releases'], ['postcss.config.*', 'src/**/*.css'], ['postcss', 'autoprefixer', 'tailwindcss'], ['plugin order', 'ESM/CJS config', 'Tailwind integration'], ['fix PostCSS config', 'repair plugin ordering', 'stabilize CSS build']),
  expert('ui-design', 'UI Design Expert Agent', 'ux', 'figma/plugin-samples', ['https://www.figma.com/best-practices/', 'https://github.com/figma/plugin-samples'], ['src/**/*.{tsx,jsx,css}', 'design-tokens.json'], ['tailwindcss', 'framer-motion'], ['visual hierarchy', 'spacing rhythm', 'contrast', 'component density', 'brand consistency'], ['improve visual hierarchy', 'repair spacing/token scale', 'align component states', 'document design choices']),
  expert('ux-research', 'UX Research Expert Agent', 'ux', 'nngroup/UX-Certification-Study-Guide', ['https://www.nngroup.com/articles/', 'https://github.com/nngroup/UX-Certification-Study-Guide'], ['README.md', 'src/**/*.{tsx,jsx}', 'docs/**'], ['playwright'], ['task flows', 'friction points', 'empty/loading/error states', 'onboarding'], ['add UX flow checklist', 'repair empty states', 'improve onboarding and form guidance']),
  expert('accessibility', 'Accessibility/WCAG Expert Agent', 'ux', 'w3c/wcag', ['https://www.w3.org/WAI/standards-guidelines/wcag/', 'https://github.com/w3c/wcag'], ['src/**/*.{tsx,jsx,html}', 'tests/**/*.spec.*'], ['axe-core', '@axe-core/playwright'], ['semantic HTML', 'keyboard flow', 'contrast', 'ARIA correctness', 'screen-reader labels'], ['fix semantic markup', 'repair ARIA usage', 'add keyboard states', 'add accessibility tests']),
  expert('motion-design', 'Motion Design Expert Agent', 'animation', 'framer/motion', ['https://motion.dev/docs', 'https://github.com/framer/motion/releases'], ['src/**/*.{tsx,jsx,css}'], ['framer-motion', 'motion'], ['animation timing', 'reduced motion', 'layout transitions', 'gesture states'], ['add polished motion', 'respect prefers-reduced-motion', 'repair layout animations', 'avoid jank']),
  expert('gsap', 'GSAP Animation Expert Agent', 'animation', 'greensock/GSAP', ['https://gsap.com/docs/v3/', 'https://github.com/greensock/GSAP/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['gsap'], ['timeline lifecycle', 'cleanup', 'ScrollTrigger', 'SSR guards'], ['fix GSAP lifecycle', 'repair animation cleanup', 'add SSR-safe guards']),
  expert('lottie', 'Lottie Expert Agent', 'animation', 'airbnb/lottie-web', ['https://airbnb.io/lottie/', 'https://github.com/airbnb/lottie-web/releases'], ['src/**/*.{ts,tsx,js,jsx}', '**/*.json'], ['lottie-web', 'lottie-react'], ['animation JSON loading', 'renderer choice', 'performance'], ['fix Lottie imports', 'repair lazy loading', 'add performance guards']),
  expert('animejs', 'Anime.js Expert Agent', 'animation', 'juliangarnier/anime', ['https://animejs.com/documentation/', 'https://github.com/juliangarnier/anime/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['animejs'], ['timeline targets', 'cleanup', 'easing/timing'], ['fix animation targets', 'repair cleanup', 'stabilize timing']),
  expert('threejs', 'Three.js/WebGL Expert Agent', 'graphics', 'mrdoob/three.js', ['https://threejs.org/docs/', 'https://github.com/mrdoob/three.js/releases'], ['src/**/*.{ts,tsx,js,jsx}', 'public/**/*.glb', 'public/**/*.gltf'], ['three', '@react-three/fiber', '@react-three/drei'], ['renderer lifecycle', 'camera/lights', 'asset loaders', 'WebGL memory', 'responsive canvas'], ['fix Three renderer setup', 'repair asset loading', 'add cleanup/dispose logic', 'optimize scene performance']),
  expert('react-three-fiber', 'React Three Fiber Expert Agent', 'graphics', 'pmndrs/react-three-fiber', ['https://docs.pmnd.rs/react-three-fiber/getting-started/introduction', 'https://github.com/pmndrs/react-three-fiber/releases'], ['src/**/*.{tsx,jsx}', 'public/**/*.glb'], ['@react-three/fiber', '@react-three/drei'], ['Canvas lifecycle', 'Suspense loaders', 'Drei helpers', 'SSR boundaries'], ['fix Canvas setup', 'repair model loading', 'add Suspense/error boundaries']),
  expert('pixijs', 'PixiJS Expert Agent', 'graphics', 'pixijs/pixijs', ['https://pixijs.com/guides', 'https://github.com/pixijs/pixijs/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['pixi.js'], ['application lifecycle', 'texture loading', 'resize handling'], ['fix Pixi lifecycle', 'repair asset loading', 'optimize rendering']),
  expert('babylonjs', 'Babylon.js Expert Agent', 'graphics', 'BabylonJS/Babylon.js', ['https://doc.babylonjs.com/', 'https://github.com/BabylonJS/Babylon.js/releases'], ['src/**/*.{ts,tsx,js,jsx}', 'public/**/*.glb'], ['@babylonjs/core'], ['engine lifecycle', 'scene setup', 'asset manager'], ['fix Babylon engine setup', 'repair scene loading', 'add cleanup']),
  expert('pdfjs', 'PDF.js Expert Agent', 'document', 'mozilla/pdf.js', ['https://mozilla.github.io/pdf.js/', 'https://github.com/mozilla/pdf.js/releases'], ['src/**/*.{ts,tsx,js,jsx}', 'public/**/*.pdf'], ['pdfjs-dist', 'react-pdf'], ['worker setup', 'CMap/fonts', 'bundler config', 'page rendering'], ['fix PDF worker config', 'repair viewer rendering', 'document asset paths']),
  expert('react-pdf', 'React PDF Expert Agent', 'document', 'diegomura/react-pdf', ['https://react-pdf.org/', 'https://github.com/diegomura/react-pdf/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['@react-pdf/renderer'], ['PDF document layout', 'font registration', 'server/browser rendering'], ['fix PDF generation', 'repair font setup', 'stabilize export route']),
  expert('docx', 'DOCX Document Expert Agent', 'document', 'dolanmiu/docx', ['https://docx.js.org/', 'https://github.com/dolanmiu/docx/releases'], ['src/**/*.{ts,js}', 'public/**/*.docx'], ['docx', 'mammoth'], ['document generation', 'template parsing', 'binary response headers'], ['fix DOCX generation', 'repair file responses', 'document template inputs']),
  expert('excel', 'Excel/Spreadsheet Expert Agent', 'document', 'exceljs/exceljs', ['https://github.com/exceljs/exceljs', 'https://github.com/exceljs/exceljs/releases'], ['src/**/*.{ts,js}', 'public/**/*.{xlsx,csv}'], ['exceljs', 'xlsx', 'papaparse'], ['worksheet schema', 'CSV parsing', 'file downloads'], ['fix spreadsheet import/export', 'repair response headers', 'document schemas']),
  expert('markdown-mdx', 'Markdown/MDX Expert Agent', 'document', 'mdx-js/mdx', ['https://mdxjs.com/docs/', 'https://github.com/mdx-js/mdx/releases'], ['**/*.md', '**/*.mdx', 'src/**/*.{ts,tsx}'], ['@mdx-js/react', 'remark', 'rehype'], ['MDX compile', 'frontmatter', 'remark/rehype plugins'], ['fix MDX pipeline', 'repair frontmatter parsing', 'document content model']),
  expert('serverless-framework', 'Serverless Framework Expert Agent', 'serverless', 'serverless/serverless', ['https://www.serverless.com/framework/docs', 'https://github.com/serverless/serverless/releases'], ['serverless.yml', 'src/**/*.{ts,js}'], ['serverless'], ['provider config', 'functions/events', 'env/secrets', 'IAM'], ['fix serverless.yml', 'repair functions/events', 'document deploy/env']),
  expert('aws-lambda', 'AWS Lambda Expert Agent', 'serverless', 'aws/aws-lambda-nodejs-runtime-interface-client', ['https://docs.aws.amazon.com/lambda/latest/dg/welcome.html', 'https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/releases'], ['src/**/*.{ts,js}', 'serverless.yml', 'template.yaml'], ['@aws-sdk/*'], ['handler shape', 'cold starts', 'timeouts', 'IAM/env'], ['fix Lambda handlers', 'repair deployment config', 'document env/IAM']),
  expert('cloudflare-pages', 'Cloudflare Pages Expert Agent', 'serverless', 'cloudflare/workers-sdk', ['https://developers.cloudflare.com/pages/', 'https://github.com/cloudflare/workers-sdk/releases'], ['wrangler.toml', 'functions/**', 'src/**/*'], ['wrangler'], ['Pages functions', 'bindings', 'compatibility date', 'build output'], ['fix Pages config', 'repair functions', 'document bindings']),
  expert('netlify-functions', 'Netlify Functions Expert Agent', 'serverless', 'netlify/functions', ['https://docs.netlify.com/functions/overview/', 'https://github.com/netlify/functions/releases'], ['netlify.toml', 'netlify/functions/**'], ['@netlify/functions'], ['function shape', 'redirects', 'env vars', 'build output'], ['fix function handlers', 'repair netlify.toml', 'document env vars']),
  expert('vercel-functions', 'Vercel Functions Expert Agent', 'serverless', 'vercel/vercel', ['https://vercel.com/docs/functions', 'https://github.com/vercel/vercel/releases'], ['api/**', 'app/api/**', 'vercel.json'], ['vercel', 'next'], ['runtime choice', 'route handlers', 'edge vs node', 'env vars'], ['fix Vercel function routes', 'repair runtime config', 'document env vars']),
  expert('sst', 'SST Serverless Expert Agent', 'serverless', 'sst/sst', ['https://sst.dev/docs/', 'https://github.com/sst/sst/releases'], ['sst.config.*', 'stacks/**'], ['sst'], ['construct config', 'stages', 'linked resources'], ['fix SST config', 'repair resource links', 'document stages/env']),
  expert('pulumi', 'Pulumi Expert Agent', 'devops', 'pulumi/pulumi', ['https://www.pulumi.com/docs/', 'https://github.com/pulumi/pulumi/releases'], ['Pulumi.yaml', 'index.ts', 'infra/**'], ['@pulumi/pulumi'], ['stack config', 'providers', 'secrets', 'resource dependencies'], ['fix Pulumi program', 'repair stack config', 'document deploy flow']),
  expert('storybook', 'Storybook Expert Agent', 'design-system', 'storybookjs/storybook', ['https://storybook.js.org/docs', 'https://github.com/storybookjs/storybook/releases'], ['.storybook/**', 'src/**/*.stories.*'], ['storybook', '@storybook/react-vite'], ['framework builder', 'stories format', 'addons', 'Vite config'], ['fix Storybook config', 'repair stories', 'document component QA']),
  expert('storybook-test-runner', 'Storybook Test Runner Expert Agent', 'test-tool', 'storybookjs/test-runner', ['https://storybook.js.org/docs/writing-tests/test-runner', 'https://github.com/storybookjs/test-runner/releases'], ['.storybook/**', 'src/**/*.stories.*'], ['@storybook/test-runner'], ['browser tests', 'accessibility checks', 'CI integration'], ['fix test runner config', 'repair stories for tests', 'document CI usage']),
  expert('tanstack-query', 'TanStack Query Expert Agent', 'library', 'TanStack/query', ['https://tanstack.com/query/latest/docs/framework/react/overview', 'https://github.com/TanStack/query/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['@tanstack/react-query'], ['query client provider', 'cache keys', 'mutation invalidation', 'loading/error states'], ['fix Query provider', 'repair cache keys', 'wire optimistic/error states']),
  expert('tanstack-router', 'TanStack Router Expert Agent', 'library', 'TanStack/router', ['https://tanstack.com/router/latest', 'https://github.com/TanStack/router/releases'], ['src/**/*.{ts,tsx}'], ['@tanstack/react-router'], ['route tree', 'loaders', 'type-safe params', 'devtools'], ['fix route config', 'repair loaders', 'stabilize route types']),
  expert('redux-toolkit', 'Redux Toolkit Expert Agent', 'library', 'reduxjs/redux-toolkit', ['https://redux-toolkit.js.org/', 'https://github.com/reduxjs/redux-toolkit/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['@reduxjs/toolkit', 'react-redux'], ['store provider', 'slices', 'RTK Query', 'serializable state'], ['fix store setup', 'repair slices', 'wire RTK Query safely']),
  expert('zustand', 'Zustand Expert Agent', 'library', 'pmndrs/zustand', ['https://zustand.docs.pmnd.rs/', 'https://github.com/pmndrs/zustand/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['zustand'], ['store shape', 'selectors', 'persistence', 'SSR hydration'], ['fix store setup', 'repair persistence', 'avoid hydration mismatch']),
  expert('react-hook-form', 'React Hook Form Expert Agent', 'library', 'react-hook-form/react-hook-form', ['https://react-hook-form.com/', 'https://github.com/react-hook-form/react-hook-form/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['react-hook-form', '@hookform/resolvers'], ['form validation', 'resolver wiring', 'default values', 'field arrays'], ['fix form wiring', 'repair validation', 'add accessible errors']),
  expert('mapbox', 'Mapbox GL Expert Agent', 'graphics', 'mapbox/mapbox-gl-js', ['https://docs.mapbox.com/mapbox-gl-js/guides/', 'https://github.com/mapbox/mapbox-gl-js/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['mapbox-gl', 'react-map-gl'], ['access token env', 'map lifecycle', 'style URLs', 'markers/layers'], ['fix map setup', 'repair token env', 'add cleanup and fallbacks']),
  expert('leaflet', 'Leaflet Expert Agent', 'graphics', 'Leaflet/Leaflet', ['https://leafletjs.com/reference.html', 'https://github.com/Leaflet/Leaflet/releases'], ['src/**/*.{ts,tsx,js,jsx}', 'public/**/*.css'], ['leaflet', 'react-leaflet'], ['CSS assets', 'map lifecycle', 'tile URLs', 'markers'], ['fix Leaflet CSS', 'repair tile config', 'document provider attribution']),
  expert('d3', 'D3 Data Visualization Expert Agent', 'graphics', 'd3/d3', ['https://d3js.org/getting-started', 'https://github.com/d3/d3/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['d3'], ['scales/axes', 'data joins', 'SVG responsiveness', 'React lifecycle'], ['fix D3 lifecycle', 'repair scales', 'make charts responsive']),
  expert('chartjs', 'Chart.js Expert Agent', 'graphics', 'chartjs/Chart.js', ['https://www.chartjs.org/docs/latest/', 'https://github.com/chartjs/Chart.js/releases'], ['src/**/*.{ts,tsx,js,jsx}'], ['chart.js', 'react-chartjs-2'], ['chart registration', 'responsive options', 'dataset shapes'], ['fix chart registration', 'repair datasets', 'stabilize responsive charts']),
];

function expert(id: string, name: string, category: LanguageExpertProfile['category'], officialGithub: string, docs: string[], filePatterns: string[], packageSignals: string[], checks: string[], repairSkills: string[]): LanguageExpertProfile {
  return { id, name, category, role: `${name} keeps NexusBrowser current with official source signals and repairs ${category} setup/build/runtime issues.`, officialGithub, docs, filePatterns, packageSignals, checks, repairSkills };
}

export function getLanguageExperts(): LanguageExpertProfile[] {
  return languageExperts;
}

export function getLanguageExpert(id: string): LanguageExpertProfile | undefined {
  return languageExperts.find((expert) => expert.id === id);
}

export async function fetchLanguageUpdate(id: string): Promise<LanguageUpdateReport> {
  const expert = getLanguageExpert(id);
  if (!expert) throw new Error(`Unknown language expert: ${id}`);
  const [owner, repoName] = expert.officialGithub.split('/');
  const headers = { accept: 'application/vnd.github+json', 'user-agent': 'NexusBrowser-LanguageExpert' };
  const [repoResponse, releaseResponse] = await Promise.all([
    fetch(`https://api.github.com/repos/${owner}/${repoName}`, { headers }).catch(() => undefined),
    fetch(`https://api.github.com/repos/${owner}/${repoName}/releases/latest`, { headers }).catch(() => undefined),
  ]);
  const repo = repoResponse?.ok ? await repoResponse.json() as any : undefined;
  const release = releaseResponse?.ok ? await releaseResponse.json() as any : undefined;
  const report: LanguageUpdateReport = {
    id: expert.id,
    name: expert.name,
    officialGithub: expert.officialGithub,
    fetchedAt: new Date().toISOString(),
    latestRelease: release ? { tag: release.tag_name, name: release.name, publishedAt: release.published_at, url: release.html_url, notes: String(release.body || '').slice(0, 4000) } : undefined,
    repo: repo ? { stars: repo.stargazers_count, openIssues: repo.open_issues_count, defaultBranch: repo.default_branch, pushedAt: repo.pushed_at } : undefined,
    prompt: buildLanguageExpertPrompt(expert, release, repo),
  };
  return report;
}

function buildLanguageExpertPrompt(expert: LanguageExpertProfile, release: any, repo: any): string {
  return `You are ${expert.name}.\n\nCategory: ${expert.category}\nRole: ${expert.role}\nOfficial GitHub source: https://github.com/${expert.officialGithub}\nOfficial docs:\n${expert.docs.map((doc) => `- ${doc}`).join('\n')}\n\nLatest official source signals:\n- Latest release: ${release?.tag_name || 'unavailable'} ${release?.name || ''}\n- Published: ${release?.published_at || 'unknown'}\n- Repository pushed at: ${repo?.pushed_at || 'unknown'}\n\nYou are used inside NexusBrowser to diagnose and repair generated apps.\n\nInspect these files when present:\n${expert.filePatterns.map((pattern) => `- ${pattern}`).join('\n')}\n\nPackage/tool signals:\n${expert.packageSignals.map((signal) => `- ${signal}`).join('\n')}\n\nCheck for:\n${expert.checks.map((check) => `- ${check}`).join('\n')}\n\nRepair skills:\n${expert.repairSkills.map((skill) => `- ${skill}`).join('\n')}\n\nRules:\n- Prefer official current behavior over stale framework assumptions.\n- Keep fixes minimal, typed, and build-verifiable.\n- Run the relevant compiler/build command after changes.\n- Never hardcode secrets.\n`;
}
