// Starter MCP server map generated by NexusBrowser.
// Wire this into @modelcontextprotocol/sdk and put credentials in environment variables.

export const discoveredTools = {

};

export async function callDiscoveredTool(name: keyof typeof discoveredTools, input: Record<string, unknown>) {
  const tool = discoveredTools[name];
  const url = new URL(tool.endpoint);

  for (const [key, value] of Object.entries(input)) {
    if (key !== 'body' && value !== undefined) url.searchParams.set(key, String(value));
  }

  const headers: Record<string, string> = { accept: 'application/json' };
  if (tool.requiresAuth && process.env.API_AUTH_TOKEN) headers.authorization = `Bearer ${process.env.API_AUTH_TOKEN}`;

  const response = await fetch(url, {
    method: tool.method,
    headers,
    body: tool.method === 'GET' ? undefined : JSON.stringify(input.body || {}),
  });

  return {
    status: response.status,
    contentType: response.headers.get('content-type'),
    body: await response.text(),
  };
}
